/*******************************************************************************
 *
 *	Copyright (C) 2008 Fujitsu Services Ltd.
 *
 *	Author: Nick Battle
 *
 *	This file is part of VDMJ.
 *
 *	VDMJ is free software: you can redistribute it and/or modify
 *	it under the terms of the GNU General Public License as published by
 *	the Free Software Foundation, either version 3 of the License, or
 *	(at your option) any later version.
 *
 *	VDMJ is distributed in the hope that it will be useful,
 *	but WITHOUT ANY WARRANTY; without even the implied warranty of
 *	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *	GNU General Public License for more details.
 *
 *	You should have received a copy of the GNU General Public License
 *	along with VDMJ.  If not, see <http://www.gnu.org/licenses/>.
 *
 ******************************************************************************/

package eu.compassresearch.core.analysis.pog.obligations;

import org.overture.pog.pub.IPOContextStack;

import eu.compassresearch.ast.actions.AWhileStatementAction;

public class CmlWhileLoopObligation extends CmlProofObligation {

		/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

		public CmlWhileLoopObligation(AWhileStatementAction stmt, IPOContextStack ctxt)
		{
			super(stmt, CmlPOType.WHILE_LOOP, ctxt);
			
			// TODO Need to decide what expression should be generated by the POG.
			// The Overture POG doesn't actually generate a PO expression at all...
			
			//stmt.getCondition()
			//stmt.getAction()
			
			// TODO what do we do with loop invariants?
			// valuetree.setPredicate(whileStmt);
//			valuetree.setContext(ctxt.getContextNodeList());
		}
	}

