package eu.compassresearch.pog.tests;


/**
 * Very simple class. Simple holds a list of file names
 * and provides them to the {@link ParameterizedBaseTest} class.
 * <br>
 * <br>
 * One day I would like the file list to be generated by
 * folder inspection.
 * @author ldc
 *
 */
public class BaseFilesProvider
{

	// Files provided as {<input>,<result}
	
	static Object[] pair1 = {"src/test/resources/basetests/CmlSatisfiability_ImpOp_Class"
		, "N/A yet"};
	
    static Object[] pair2 = {"src/test/resources/basetests/CmlSatisfiability_ImpOp_Proc"
    	, "N/A yet."};
    
	static Object[] pair3 = {"src/test/resources/basetests/FuncPostCondition"
		, "N/A yet."};
	
	static Object[] pair4 = {"src/test/resources/basetests/FunctionApply"
		, "N/A yet."};
	
	static Object[] pair5 = {"src/test/resources/basetests/MapApply"
		, "N/A yet."};
	
	static Object[] pair6 = {"src/test/resources/basetests/MapSeqofCompatible"
		, "N/A yet."};
	
	static Object[] pair7 = {"src/test/resources/basetests/NonEmptySeq"
		, "N/A yet."};
	
	static Object[] pair8 = {"src/test/resources/basetests/NonZero"
		, "N/A yet."};
	
	static Object[] pair9 = {"src/test/resources/basetests/Satisfiability_ImpFunc"
		, "N/A yet."};
	
	static Object[] pair10 = {"src/test/resources/basetests/Subtype_Inv"
		, "N/A yet."};
	
	static Object[] pair11 = {"src/test/resources/basetests/TupleSelection"
		, "N/A yet."};


	public static Object[][] files = new Object[][] { 
		pair1,
		pair2,
		pair3,
		pair4,
		pair5,
		pair6,
		pair7,
		pair8,
		pair9,
		pair10,
		pair11
	} ;
	

}
