/**
 * 
 */
package eu.compassresearch.ide.faulttolerance;

import java.util.ResourceBundle;

/**
 * @author Andr&eacute; Didier (<a href=
 *         "mailto:alrd@cin.ufpe.br?Subject=Package eu.compassresearch.ide.faulttolerance, class Message"
 *         >alrd@cin.ufpe.br</a>)
 * 
 */
public enum Message {
	DIVERGENCE_FREE_JOB, SEMIFAIRNESS_JOB, FULL_FAULT_TOLERANCE_JOB, LIMITED_FAULT_TOLERANCE_JOB, STARTING_MODEL_CHECKING, CHECKING_PREREQUISITES, LIMIT_EXPRESSION, FULL_FAULT_TOLERANCE_SUCCESS, FULL_FAULT_TOLERANCE_ERROR, LIMITED_FAULT_TOLERANCE_SUCCESS, LIMITED_FAULT_TOLERANCE_ERROR, NO_PROJECT_SELECTED, MARKER_LOCATION, DIVERGENCE_FREE_SUCCESS, DIVERGENCE_FREE_ERROR, SEMIFAIR_SUCCESS, SEMIFAIR_ERROR, DIVERGENCE_FREE_SEMIFAIR_ERROR, LIMIT_EXPRESSION_DIALOG_TITLE, LIMIT_EXPRESSION_DIALOG_MESSAGE, CML_PROCESSES_TEMPLATE, BASE_CML_TEMPLATE, FOLDER_NAME, FILES_MANAGEMENT_JOB, STARTING_FAULT_TOLERANCE_FILES_MANAGEMENT, UNABLE_TO_CREATE_FAULT_TOLERANCE_PROCESSES_FILE, UNABLE_TO_CREATE_FAULT_TOLERANCE_BASE_FILE, UNABLE_TO_CREATE_FAULT_TOLERANCE_FOLDER, BASE_CML_FILE_NAME, CML_PROCESSES_FILE_NAME;

	public String format(Object... params) {
		return String.format(
				ResourceBundle.getBundle("Message").getString(this.name()),
				params);
	}
}
