/* The following code was generated by JFlex 1.4.3 on 2/24/12 3:35 PM */

package eu.compassresearch.cml.compiler;
import java.util.LinkedList;
import java.util.List;
import java.util.HashMap;
import java.util.Vector;
import java.util.Stack;
import eu.compassresearch.cml.compiler.CmlParser.Lexer;
import eu.compassresearch.cml.compiler.CmlParser.Location;

/*
class CmlContext {
  
}
*/
class LexicographicalRuntimeException extends RuntimeException
{
  private int pos,line;
  private  String value;
  public LexicographicalRuntimeException(String chars)
    {
      this.pos = CMLToken.curPos;
      this.line = CMLToken.curLine;
      this.value = chars;
    }
  
  @Override
    public String toString()
    {
      return "Offending syntax "+(value != null ? "starting with \""+value+"\" ":"")+"found at line "+(line+1)+" position "+(pos+1);
    }
}

class CmlLexeme {
  
    private Position startPos;
    private Position endPos;
    protected  String value;
    private int lex;

    public CmlLexeme(Position startPos, Position endPos, int lex, String value)
    {
	this.value = value;
	this.startPos = startPos;
	this.endPos = endPos;
	this.lex = lex;
    }

    public Position getStartPos()
    {
	return startPos;
    }

    public Position getEndPos()
    {
	return endPos;
    }

    public int getLexValue()
    {
	return lex;
    }
    
    public String getValue()
    {
	return this.value;
    }

    public String toString()
    {
	return value + " " + startPos;
    }
}

class CMLToken {
  public static int curLine;
  public static int curPos; 

  private int line;
  private int pos;
  protected  String value;
  public CMLToken(String value)
  {
    this.value = value;
    this.line = line;
    this.pos = pos;
  }

  public String getValue()
  {
    return this.value;
  }

  public static void main(String[] args) throws Exception
  {
    try{
    new CmlLexer(System.in).yylex();
    } catch (LexicographicalRuntimeException e)
	{
	  System.out.println(e);
	}
  }
}

class StringToken extends CMLToken {
  static StringToken currentString;
  private StringBuilder currentLine;
  private List<String> lines = new LinkedList<String>();

  private int endLine;
  private int endPos;

  public StringToken(int startLine, int startPos)
  {
    super("\"");
    currentLine = new StringBuilder();
  }

  public void append(String chars)
  {
    currentLine.append(chars);
  }

  public void newLine()
  {
    lines.add(currentLine.toString());
    currentLine = new StringBuilder();
  }

  public void endString(int line, int pos)
  {
    lines.add(currentLine.toString());
    this.endLine = line;
    this.endPos = pos;
    StringBuilder sb = new StringBuilder();
    for(String s : lines)
      sb.append(s);
    super.value = sb.toString();
    lines=null;
  }
}

class CommentBlock extends CMLToken {
  static CommentBlock current;
  private int level;
  StringBuilder content;

  public CommentBlock()
  {
    super("--");
    current=this;
    content=new StringBuilder();
    level = 1;
  }

  public void appendLine(String line)
  {
    this.content.append(line);
  }

  public void increaseLevel()
  {
    level ++;
  }

  public boolean decreaseLevel()
  {
    level--;
    return level == 0;
  }
}


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 2/24/12 3:35 PM from the specification file
 * <tt>cml.lex</tt>
 */
public class CmlLexer implements Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;
  private static final String ZZ_NL = System.getProperty("line.separator");

  /** lexical states */
  public static final int OPERATIONS = 10;
  public static final int TYPES = 4;
  public static final int YYINITIAL = 0;
  public static final int ACTIONS = 16;
  public static final int CHANSETS = 14;
  public static final int STATE = 6;
  public static final int PROCESS = 2;
  public static final int CHANNELS = 12;
  public static final int COMMENT = 18;
  public static final int FUNCTIONS = 8;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7, 
     8,  8,  9, 9
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\44\1\43\1\0\1\44\1\42\22\0\1\67\1\77\1\0"+
    "\1\11\2\0\1\75\1\14\1\110\1\107\1\46\1\55\1\104\1\52"+
    "\1\106\1\45\1\4\1\114\10\4\1\51\1\50\1\105\1\47\1\54"+
    "\1\76\1\101\1\2\1\25\1\20\1\32\1\22\1\36\1\27\1\40"+
    "\1\30\2\10\1\41\1\10\1\31\1\17\1\15\1\10\1\16\1\24"+
    "\1\34\1\7\3\10\1\35\1\10\1\102\1\5\1\103\1\111\1\113"+
    "\1\12\1\3\1\26\1\21\1\33\1\23\1\37\1\27\1\115\1\66"+
    "\1\10\1\112\1\70\1\65\1\62\1\53\1\63\1\10\1\56\1\64"+
    "\1\61\1\6\1\100\1\57\1\60\1\71\1\10\1\72\1\73\1\74"+
    "\1\13\201\0\ufef1\1\17\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\12\0\1\1\1\2\2\0\1\1\2\3\1\0\7\1"+
    "\1\4\1\1\1\5\1\6\1\7\2\1\1\10\1\11"+
    "\1\4\1\12\1\13\1\14\1\1\1\15\1\16\6\1"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\4\1\13\1\1\1\14"+
    "\1\16\4\1\1\4\2\1\1\33\2\0\1\4\1\34"+
    "\1\33\1\14\1\35\1\36\1\37\1\1\1\40\1\23"+
    "\2\41\1\0\1\1\1\42\1\43\12\1\1\44\1\45"+
    "\1\46\1\47\1\50\1\51\1\52\1\53\10\1\1\54"+
    "\1\55\1\0\1\56\1\57\1\60\1\33\1\61\1\62"+
    "\1\63\5\1\1\60\1\1\1\64\1\65\1\66\1\67"+
    "\1\70\1\71\1\1\1\72\1\73\1\41\1\0\4\1"+
    "\1\74\3\1\1\75\2\1\1\76\1\77\2\1\1\100"+
    "\1\101\1\1\1\102\1\103\1\0\1\104\1\105\1\106"+
    "\1\1\1\107\1\1\1\0\1\110\1\111\1\1\1\112"+
    "\1\0\7\1\1\113\1\114\1\115\1\1\1\116\2\0"+
    "\1\117\1\1\2\0\1\1\1\0\5\1\1\120\1\121"+
    "\1\1\1\122\2\0\1\1\2\0\7\1\1\123\1\124"+
    "\1\1\2\0\1\125\1\126\1\127\4\1\1\130\2\0"+
    "\1\1\1\131\1\132\1\1\2\0\1\1\1\133\2\0"+
    "\1\134\24\0\1\135\6\0\1\136";

  private static int [] zzUnpackAction() {
    int [] result = new int[272];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\116\0\234\0\352\0\u0138\0\u0186\0\u01d4\0\u0222"+
    "\0\u0270\0\u02be\0\u030c\0\u035a\0\u03a8\0\u03f6\0\u0444\0\u0492"+
    "\0\u04e0\0\u052e\0\u057c\0\u05ca\0\u0618\0\u0666\0\u06b4\0\u0702"+
    "\0\u0750\0\u04e0\0\u079e\0\u03a8\0\u04e0\0\u04e0\0\u07ec\0\u083a"+
    "\0\u052e\0\u04e0\0\u0888\0\u04e0\0\u08d6\0\u04e0\0\u0924\0\u0972"+
    "\0\u09c0\0\u0a0e\0\u0a5c\0\u0aaa\0\u0af8\0\u0b46\0\u0b94\0\u04e0"+
    "\0\u04e0\0\u04e0\0\u04e0\0\u04e0\0\u04e0\0\u04e0\0\u0be2\0\u0c30"+
    "\0\u04e0\0\u04e0\0\u04e0\0\u0c7e\0\u0ccc\0\u0d1a\0\u0d68\0\u0db6"+
    "\0\u0e04\0\u0e52\0\u0ea0\0\u0eee\0\u0f3c\0\u0f8a\0\u0fd8\0\u04e0"+
    "\0\u1026\0\u1074\0\u10c2\0\u04e0\0\u0ccc\0\u1110\0\u04e0\0\u04e0"+
    "\0\u04e0\0\u115e\0\u04e0\0\u11ac\0\u04e0\0\u11fa\0\u1248\0\u1296"+
    "\0\u12e4\0\u04e0\0\u1332\0\u1380\0\u13ce\0\u141c\0\u146a\0\u14b8"+
    "\0\u1506\0\u1554\0\u15a2\0\u15f0\0\u04e0\0\u04e0\0\u04e0\0\u04e0"+
    "\0\u163e\0\u030c\0\u04e0\0\u04e0\0\u168c\0\u16da\0\u1728\0\u1776"+
    "\0\u17c4\0\u1812\0\u1860\0\u18ae\0\u18fc\0\u04e0\0\u194a\0\u04e0"+
    "\0\u04e0\0\u04e0\0\u163e\0\u030c\0\u04e0\0\u04e0\0\u1998\0\u19e6"+
    "\0\u1a34\0\u1a82\0\u1ad0\0\u1b1e\0\u1b6c\0\u030c\0\u030c\0\u04e0"+
    "\0\u04e0\0\u04e0\0\u04e0\0\u1bba\0\u04e0\0\u04e0\0\u1c08\0\u1c56"+
    "\0\u1ca4\0\u1cf2\0\u1d40\0\u1d8e\0\u030c\0\u1ddc\0\u1e2a\0\u1e78"+
    "\0\u030c\0\u1ec6\0\u1f14\0\u04e0\0\u030c\0\u1f62\0\u1fb0\0\u1ffe"+
    "\0\u030c\0\u204c\0\u030c\0\u030c\0\u209a\0\u030c\0\u04e0\0\u04e0"+
    "\0\u20e8\0\u030c\0\u2136\0\u2184\0\u030c\0\u04e0\0\u21d2\0\u030c"+
    "\0\u2220\0\u226e\0\u22bc\0\u230a\0\u2358\0\u23a6\0\u23f4\0\u2442"+
    "\0\u030c\0\u030c\0\u030c\0\u2490\0\u030c\0\u24de\0\u252c\0\u030c"+
    "\0\u257a\0\u25c8\0\u2616\0\u2664\0\u26b2\0\u2700\0\u274e\0\u279c"+
    "\0\u27ea\0\u2838\0\u030c\0\u030c\0\u2886\0\u030c\0\u28d4\0\u2922"+
    "\0\u2970\0\u29be\0\u2a0c\0\u2a5a\0\u2aa8\0\u2af6\0\u2b44\0\u2b92"+
    "\0\u2be0\0\u2c2e\0\u04e0\0\u04e0\0\u2c7c\0\u2cca\0\u2d18\0\u030c"+
    "\0\u030c\0\u030c\0\u2d66\0\u2db4\0\u2e02\0\u2e50\0\u030c\0\u2e9e"+
    "\0\u2eec\0\u2f3a\0\u030c\0\u030c\0\u2f88\0\u2fd6\0\u3024\0\u3072"+
    "\0\u030c\0\u30c0\0\u310e\0\u030c\0\u315c\0\u31aa\0\u31f8\0\u3246"+
    "\0\u3294\0\u32e2\0\u3330\0\u337e\0\u33cc\0\u341a\0\u3468\0\u34b6"+
    "\0\u3504\0\u3552\0\u35a0\0\u35ee\0\u363c\0\u368a\0\u36d8\0\u3726"+
    "\0\u04e0\0\u3774\0\u37c2\0\u3810\0\u385e\0\u38ac\0\u38fa\0\u04e0";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[272];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\3\13\1\14\1\15\3\13\1\16\3\0\1\17"+
    "\24\13\1\20\2\21\1\22\5\0\1\13\2\0\5\13"+
    "\1\17\3\13\1\21\2\13\6\0\1\13\11\0\1\13"+
    "\1\0\1\14\1\13\1\0\1\13\2\23\1\14\1\15"+
    "\3\13\1\16\3\0\2\13\1\24\2\25\2\26\1\13"+
    "\2\27\5\13\1\30\1\13\2\31\2\13\1\20\2\21"+
    "\1\22\1\0\1\32\3\0\1\24\2\0\3\13\1\30"+
    "\5\13\1\21\2\13\6\0\1\13\11\0\1\13\1\0"+
    "\1\14\1\13\1\0\1\13\1\23\1\33\1\14\1\34"+
    "\3\13\1\16\1\35\1\36\1\0\2\13\1\24\1\25"+
    "\1\37\2\26\2\13\1\40\5\13\1\30\1\13\2\31"+
    "\2\13\1\20\2\21\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\1\51\1\52\2\13\1\53\1\54"+
    "\1\13\1\55\1\56\1\57\1\21\2\13\1\60\1\61"+
    "\1\62\1\63\1\0\1\63\1\13\1\0\1\64\1\65"+
    "\1\66\1\67\1\70\1\71\1\72\1\73\1\13\1\0"+
    "\1\14\1\13\1\0\1\13\1\23\1\33\1\14\1\34"+
    "\3\13\1\16\1\35\1\36\1\0\2\13\1\24\1\25"+
    "\1\37\2\26\2\13\1\40\5\13\1\30\1\13\2\31"+
    "\2\13\1\20\2\21\1\41\1\42\1\74\1\44\1\75"+
    "\1\46\1\76\1\50\1\51\1\52\2\13\1\53\1\54"+
    "\1\13\1\55\1\56\1\57\1\21\2\13\1\60\1\61"+
    "\1\62\1\63\1\0\1\63\1\13\1\0\1\64\1\65"+
    "\1\66\1\67\1\70\1\71\1\72\1\73\1\13\1\0"+
    "\1\14\1\13\1\0\1\13\1\23\1\33\1\14\1\34"+
    "\3\13\1\16\1\35\1\36\1\0\2\13\1\24\1\25"+
    "\1\37\2\26\2\13\1\40\5\13\1\30\1\13\2\31"+
    "\2\13\1\20\2\21\1\41\1\42\1\74\1\44\1\75"+
    "\1\77\1\47\1\50\1\100\1\52\2\13\1\53\1\54"+
    "\1\101\1\55\1\102\1\103\1\21\2\13\1\60\1\61"+
    "\1\62\1\63\1\0\1\63\1\13\1\0\1\64\1\65"+
    "\1\66\1\67\1\70\1\71\1\72\1\73\1\13\1\0"+
    "\1\14\1\13\1\0\1\13\1\23\1\33\1\14\1\34"+
    "\3\13\1\16\1\35\1\36\1\0\2\13\1\24\1\25"+
    "\1\37\1\26\1\104\2\13\1\40\5\13\1\30\1\13"+
    "\2\31\2\13\1\20\2\21\1\41\1\42\1\105\1\44"+
    "\1\75\1\46\1\47\1\50\1\51\1\106\1\107\1\13"+
    "\1\53\1\54\1\101\1\55\1\102\1\103\1\21\2\13"+
    "\1\60\1\61\1\62\1\63\1\0\1\63\1\13\1\0"+
    "\1\64\1\65\1\66\1\67\1\70\1\71\1\72\1\73"+
    "\1\13\1\0\1\14\1\13\1\0\1\13\2\23\1\14"+
    "\1\15\3\13\1\16\3\0\2\13\1\24\2\25\2\26"+
    "\10\13\1\30\1\13\2\31\2\13\1\20\2\21\1\22"+
    "\3\0\1\110\1\0\1\24\2\0\3\13\1\30\5\13"+
    "\1\21\2\13\6\0\1\13\3\0\1\66\5\0\1\13"+
    "\1\0\1\14\1\13\1\0\1\13\2\23\1\14\1\15"+
    "\3\13\1\16\3\0\2\13\1\24\2\25\2\26\10\13"+
    "\1\30\1\13\2\31\2\13\1\20\2\21\1\22\1\0"+
    "\1\32\1\0\1\110\1\0\1\24\2\0\3\13\1\30"+
    "\5\13\1\21\2\13\1\111\1\112\4\0\1\13\3\0"+
    "\1\66\5\0\1\13\1\0\1\14\1\13\1\0\1\13"+
    "\1\23\1\33\1\14\1\34\3\13\1\16\1\35\1\36"+
    "\1\0\2\13\1\24\1\25\1\37\2\26\2\13\1\40"+
    "\5\13\1\30\1\13\2\31\2\13\1\20\2\21\1\41"+
    "\1\42\1\113\1\114\1\115\1\116\1\47\1\50\1\51"+
    "\1\52\2\13\1\53\1\54\1\13\1\55\1\56\1\57"+
    "\1\21\2\13\1\60\1\61\1\62\1\117\1\120\1\121"+
    "\1\122\1\123\1\124\1\65\1\66\1\67\1\70\1\71"+
    "\1\72\1\73\1\13\1\0\1\14\1\13\46\125\1\126"+
    "\47\125\1\0\4\13\1\15\3\13\1\16\2\0\26\13"+
    "\11\0\1\13\2\0\11\13\1\0\2\13\6\0\1\13"+
    "\11\0\4\13\4\0\1\14\107\0\1\14\7\0\2\127"+
    "\110\0\2\13\2\0\3\13\4\0\25\13\11\0\1\13"+
    "\2\0\11\13\1\0\2\13\6\0\1\13\11\0\1\13"+
    "\2\0\1\13\1\0\4\13\1\15\3\13\1\16\2\0"+
    "\2\13\1\130\23\13\11\0\1\13\2\0\1\130\10\13"+
    "\1\0\2\13\6\0\1\13\11\0\4\13\43\0\1\21"+
    "\235\0\1\131\1\132\50\0\4\13\1\15\3\13\1\16"+
    "\2\0\4\13\2\133\20\13\11\0\1\13\2\0\11\13"+
    "\1\0\2\13\6\0\1\13\11\0\4\13\1\0\4\13"+
    "\1\15\3\13\1\16\2\0\1\13\1\134\24\13\11\0"+
    "\1\13\2\0\5\13\1\134\3\13\1\0\2\13\6\0"+
    "\1\13\11\0\4\13\1\0\4\13\1\15\3\13\1\16"+
    "\2\0\24\13\1\135\1\13\11\0\1\13\2\0\11\13"+
    "\1\0\2\13\6\0\1\13\11\0\3\13\1\135\1\0"+
    "\4\13\1\15\3\13\1\16\2\0\15\13\1\136\10\13"+
    "\11\0\1\13\2\0\4\13\1\136\4\13\1\0\2\13"+
    "\6\0\1\13\11\0\4\13\1\0\4\13\1\15\3\13"+
    "\1\16\2\0\6\13\2\137\16\13\11\0\1\13\2\0"+
    "\11\13\1\0\2\13\6\0\1\13\11\0\4\13\1\0"+
    "\4\13\1\15\3\13\1\16\2\0\21\13\1\140\4\13"+
    "\11\0\1\13\2\0\11\13\1\0\1\13\1\140\6\0"+
    "\1\13\11\0\4\13\1\0\4\13\1\15\2\141\1\13"+
    "\1\16\2\0\26\13\11\0\1\13\2\0\11\13\1\0"+
    "\2\13\6\0\1\13\11\0\4\13\1\0\4\13\1\15"+
    "\3\13\1\16\2\0\4\13\2\133\20\13\11\0\1\13"+
    "\2\0\4\13\1\142\4\13\1\0\2\13\6\0\1\13"+
    "\11\0\4\13\1\0\4\13\1\15\3\13\1\16\2\0"+
    "\24\13\1\135\1\13\11\0\1\13\2\0\11\13\1\0"+
    "\2\13\6\0\1\13\11\0\3\13\1\143\1\0\4\13"+
    "\1\15\3\13\1\16\2\0\26\13\11\0\1\144\2\0"+
    "\11\13\1\0\2\13\6\0\1\13\11\0\4\13\47\0"+
    "\1\145\4\0\1\146\41\0\47\110\1\147\1\0\1\150"+
    "\1\151\32\110\1\0\10\110\1\0\4\13\1\15\3\13"+
    "\1\16\2\0\1\13\1\134\24\13\11\0\1\13\2\0"+
    "\1\152\4\13\1\134\3\13\1\0\2\13\6\0\1\13"+
    "\11\0\4\13\47\0\1\153\123\0\1\154\41\0\2\13"+
    "\1\155\1\13\1\15\3\13\1\16\2\0\7\13\1\156"+
    "\16\13\11\0\1\13\2\0\11\13\1\0\2\13\6\0"+
    "\1\13\11\0\4\13\1\0\4\13\1\15\3\13\1\16"+
    "\2\0\21\13\1\140\4\13\11\0\1\157\2\0\11\13"+
    "\1\0\1\13\1\140\6\0\1\13\11\0\4\13\1\0"+
    "\2\13\1\160\1\13\1\15\3\13\1\16\2\0\26\13"+
    "\11\0\1\161\2\0\11\13\1\0\2\13\6\0\1\13"+
    "\11\0\4\13\1\0\4\13\1\15\3\13\1\16\2\0"+
    "\7\13\1\162\16\13\11\0\1\13\2\0\11\13\1\0"+
    "\2\13\6\0\1\13\11\0\4\13\1\0\4\13\1\15"+
    "\3\13\1\16\2\0\26\13\11\0\1\13\2\0\11\13"+
    "\1\0\2\13\6\0\1\13\11\0\1\163\3\13\1\0"+
    "\4\13\1\15\3\13\1\16\2\0\26\13\11\0\1\13"+
    "\2\0\4\13\1\164\4\13\1\0\2\13\6\0\1\13"+
    "\11\0\4\13\47\0\1\165\1\0\1\166\1\167\1\0"+
    "\1\170\52\0\1\171\153\0\1\172\4\0\1\146\41\0"+
    "\47\110\1\147\1\0\1\150\1\173\32\110\1\0\10\110"+
    "\1\0\4\13\1\15\3\13\1\16\2\0\1\13\1\134"+
    "\21\13\1\174\2\13\11\0\1\13\2\0\1\152\4\13"+
    "\1\134\3\13\1\0\2\13\6\0\1\13\11\0\4\13"+
    "\54\0\1\175\115\0\1\176\1\154\41\0\4\13\1\15"+
    "\3\13\1\16\2\0\26\13\11\0\1\177\2\0\1\200"+
    "\10\13\1\0\2\13\6\0\1\13\11\0\4\13\1\0"+
    "\4\13\1\15\3\13\1\16\2\0\7\13\1\201\16\13"+
    "\11\0\1\13\2\0\11\13\1\0\2\13\6\0\1\13"+
    "\11\0\1\163\3\13\1\0\4\13\1\15\3\13\1\16"+
    "\2\0\26\13\11\0\1\13\2\0\4\13\1\164\1\13"+
    "\1\202\2\13\1\0\2\13\6\0\1\13\11\0\4\13"+
    "\1\0\4\13\1\15\3\13\1\16\2\0\15\13\1\136"+
    "\10\13\11\0\1\13\2\0\2\13\1\203\1\13\1\136"+
    "\4\13\1\0\2\13\6\0\1\13\11\0\4\13\47\0"+
    "\1\204\4\0\1\146\42\0\2\13\1\155\1\13\1\15"+
    "\3\13\1\16\2\0\7\13\1\205\7\13\1\206\6\13"+
    "\11\0\1\13\2\0\11\13\1\0\2\13\6\0\1\13"+
    "\11\0\4\13\1\0\4\13\1\15\3\13\1\16\2\0"+
    "\26\13\11\0\1\13\2\0\1\207\10\13\1\0\2\13"+
    "\6\0\1\13\11\0\4\13\73\0\1\210\116\0\1\211"+
    "\70\0\1\172\4\0\1\212\115\0\1\213\42\0\2\13"+
    "\1\214\1\13\1\15\3\13\1\16\2\0\26\13\11\0"+
    "\1\13\2\0\11\13\1\0\2\13\6\0\1\13\11\0"+
    "\4\13\103\0\1\215\12\0\45\125\1\216\1\217\47\125"+
    "\2\0\3\220\13\0\4\220\1\0\2\220\3\0\2\220"+
    "\2\0\2\220\54\0\1\220\2\0\4\13\1\15\3\13"+
    "\1\16\2\0\3\13\1\221\22\13\11\0\1\221\2\0"+
    "\11\13\1\0\2\13\6\0\1\13\11\0\4\13\43\131"+
    "\1\0\52\131\1\0\4\13\1\15\3\13\1\16\2\0"+
    "\20\13\1\222\5\13\11\0\1\13\2\0\3\13\1\222"+
    "\5\13\1\0\2\13\6\0\1\13\11\0\4\13\1\0"+
    "\4\13\1\15\3\13\1\16\2\0\6\13\2\223\16\13"+
    "\11\0\1\13\2\0\11\13\1\0\2\13\6\0\1\13"+
    "\11\0\4\13\1\0\1\13\2\224\1\13\1\15\3\13"+
    "\1\16\2\0\26\13\11\0\1\13\2\0\11\13\1\0"+
    "\2\13\6\0\1\13\11\0\4\13\1\0\4\13\1\15"+
    "\3\13\1\16\2\0\16\13\2\225\6\13\11\0\1\13"+
    "\2\0\11\13\1\0\2\13\6\0\1\13\11\0\4\13"+
    "\1\0\4\13\1\15\3\13\1\16\2\0\13\13\1\226"+
    "\12\13\11\0\1\13\2\0\11\13\1\0\2\13\6\0"+
    "\1\13\11\0\4\13\1\0\4\13\1\15\3\13\1\16"+
    "\2\0\1\13\1\227\24\13\11\0\1\13\2\0\5\13"+
    "\1\227\3\13\1\0\2\13\6\0\1\13\11\0\4\13"+
    "\1\0\4\13\1\15\3\13\1\16\2\0\15\13\1\230"+
    "\10\13\11\0\1\13\2\0\4\13\1\230\4\13\1\0"+
    "\2\13\6\0\1\13\11\0\4\13\1\0\4\13\1\15"+
    "\3\13\1\16\2\0\17\13\1\231\6\13\11\0\1\13"+
    "\2\0\11\13\1\0\2\13\6\0\1\13\11\0\4\13"+
    "\1\0\1\13\1\224\1\232\1\13\1\15\3\13\1\16"+
    "\2\0\26\13\11\0\1\13\2\0\11\13\1\0\2\13"+
    "\6\0\1\13\11\0\4\13\1\0\4\13\1\15\3\13"+
    "\1\16\2\0\26\13\11\0\1\233\2\0\11\13\1\0"+
    "\2\13\6\0\1\13\11\0\4\13\54\0\1\234\42\0"+
    "\4\13\1\15\3\13\1\16\2\0\26\13\11\0\1\13"+
    "\2\0\3\13\1\235\5\13\1\0\2\13\6\0\1\13"+
    "\11\0\4\13\1\0\2\13\1\236\1\13\1\15\3\13"+
    "\1\16\2\0\26\13\11\0\1\13\2\0\11\13\1\0"+
    "\2\13\6\0\1\13\11\0\4\13\1\0\4\13\1\15"+
    "\3\13\1\16\2\0\26\13\11\0\1\13\2\0\11\13"+
    "\1\0\2\13\6\0\1\13\11\0\1\237\3\13\1\0"+
    "\4\13\1\15\3\13\1\16\2\0\26\13\11\0\1\13"+
    "\2\0\3\13\1\240\5\13\1\0\2\13\6\0\1\13"+
    "\11\0\4\13\1\0\4\13\1\15\3\13\1\16\2\0"+
    "\26\13\11\0\1\13\2\0\3\13\1\241\5\13\1\0"+
    "\2\13\6\0\1\13\11\0\4\13\1\0\4\13\1\15"+
    "\3\13\1\16\2\0\26\13\11\0\1\13\2\0\3\13"+
    "\1\242\5\13\1\0\2\13\6\0\1\13\11\0\4\13"+
    "\1\0\4\13\1\15\3\13\1\16\2\0\26\13\11\0"+
    "\1\13\2\0\11\13\1\0\2\13\6\0\1\13\11\0"+
    "\1\13\1\243\2\13\1\0\4\13\1\15\3\13\1\16"+
    "\2\0\26\13\11\0\1\13\2\0\3\13\1\244\5\13"+
    "\1\245\2\13\6\0\1\246\11\0\4\13\54\0\1\247"+
    "\112\0\1\250\45\0\4\13\1\15\3\13\1\16\2\0"+
    "\26\13\11\0\1\13\2\0\6\13\1\251\2\13\1\0"+
    "\2\13\6\0\1\13\11\0\4\13\1\0\4\13\1\15"+
    "\3\13\1\16\2\0\7\13\1\252\16\13\11\0\1\13"+
    "\2\0\11\13\1\0\2\13\6\0\1\13\11\0\4\13"+
    "\1\0\2\13\1\253\1\13\1\15\3\13\1\16\2\0"+
    "\26\13\11\0\1\13\2\0\11\13\1\0\2\13\6\0"+
    "\1\13\11\0\4\13\1\0\4\13\1\15\3\13\1\16"+
    "\2\0\26\13\11\0\1\13\2\0\11\13\1\254\2\13"+
    "\6\0\1\13\11\0\4\13\1\0\4\13\1\15\3\13"+
    "\1\16\2\0\26\13\11\0\1\13\2\0\3\13\1\255"+
    "\5\13\1\0\2\13\6\0\1\13\11\0\4\13\54\0"+
    "\1\256\42\0\2\13\1\236\1\13\1\15\3\13\1\16"+
    "\2\0\26\13\11\0\1\13\2\0\3\13\1\257\5\13"+
    "\1\0\2\13\6\0\1\13\11\0\4\13\1\0\4\13"+
    "\1\15\3\13\1\16\2\0\26\13\11\0\1\13\2\0"+
    "\1\260\10\13\1\0\2\13\6\0\1\13\11\0\4\13"+
    "\45\125\1\0\1\217\47\125\2\0\3\261\13\0\4\261"+
    "\1\0\2\261\3\0\2\261\2\0\2\261\54\0\1\261"+
    "\2\0\4\13\1\15\3\13\1\16\2\0\4\13\2\262"+
    "\20\13\11\0\1\13\2\0\11\13\1\0\2\13\6\0"+
    "\1\13\11\0\4\13\1\0\4\13\1\15\3\13\1\16"+
    "\2\0\14\13\1\263\11\13\11\0\1\13\2\0\10\13"+
    "\1\263\1\0\2\13\6\0\1\13\11\0\4\13\1\0"+
    "\4\13\1\15\3\13\1\16\2\0\2\13\1\264\23\13"+
    "\11\0\1\13\2\0\1\264\10\13\1\0\2\13\6\0"+
    "\1\13\11\0\4\13\1\0\4\13\1\15\3\13\1\16"+
    "\2\0\15\13\1\265\10\13\11\0\1\13\2\0\4\13"+
    "\1\265\4\13\1\0\2\13\6\0\1\13\11\0\4\13"+
    "\1\0\4\13\1\15\3\13\1\16\2\0\14\13\1\266"+
    "\11\13\11\0\1\13\2\0\10\13\1\266\1\0\2\13"+
    "\6\0\1\13\11\0\4\13\1\0\4\13\1\15\3\13"+
    "\1\16\2\0\6\13\2\267\16\13\11\0\1\13\2\0"+
    "\11\13\1\0\2\13\6\0\1\13\11\0\4\13\1\0"+
    "\4\13\1\15\3\13\1\16\2\0\4\13\2\270\20\13"+
    "\11\0\1\13\2\0\11\13\1\0\2\13\6\0\1\13"+
    "\11\0\4\13\1\0\4\13\1\15\3\13\1\16\2\0"+
    "\15\13\1\265\10\13\11\0\1\13\2\0\1\271\3\13"+
    "\1\265\4\13\1\0\2\13\6\0\1\13\11\0\4\13"+
    "\1\0\4\13\1\15\3\13\1\16\2\0\26\13\11\0"+
    "\1\13\2\0\11\13\1\0\1\272\1\13\6\0\1\13"+
    "\11\0\4\13\1\0\4\13\1\15\3\13\1\16\2\0"+
    "\26\13\11\0\1\13\2\0\11\13\1\0\1\273\1\13"+
    "\6\0\1\13\11\0\4\13\1\0\4\13\1\15\3\13"+
    "\1\16\2\0\7\13\1\274\16\13\11\0\1\13\2\0"+
    "\11\13\1\0\2\13\6\0\1\13\11\0\4\13\1\0"+
    "\4\13\1\15\3\13\1\16\2\0\26\13\11\0\1\13"+
    "\2\0\11\13\1\0\2\13\6\0\1\13\11\0\2\13"+
    "\1\275\1\13\1\0\4\13\1\15\3\13\1\16\2\0"+
    "\26\13\11\0\1\13\2\0\11\13\1\276\2\13\6\0"+
    "\1\13\11\0\4\13\64\0\1\277\32\0\4\13\1\15"+
    "\3\13\1\16\2\0\26\13\11\0\1\13\2\0\3\13"+
    "\1\300\5\13\1\0\2\13\6\0\1\13\11\0\4\13"+
    "\1\0\4\13\1\15\3\13\1\16\2\0\26\13\11\0"+
    "\1\13\2\0\6\13\1\301\2\13\1\0\2\13\6\0"+
    "\1\13\11\0\4\13\62\0\1\302\1\0\1\303\32\0"+
    "\4\13\1\15\1\304\2\13\1\16\2\0\26\13\11\0"+
    "\1\13\2\0\11\13\1\0\2\13\6\0\1\13\11\0"+
    "\4\13\2\0\3\305\13\0\4\305\1\0\2\305\3\0"+
    "\2\305\2\0\2\305\54\0\1\305\2\0\4\13\1\15"+
    "\3\13\1\16\2\0\6\13\2\306\16\13\11\0\1\13"+
    "\2\0\11\13\1\0\2\13\6\0\1\13\11\0\4\13"+
    "\1\0\4\13\1\15\3\13\1\16\2\0\3\13\1\307"+
    "\22\13\11\0\1\307\2\0\11\13\1\0\2\13\6\0"+
    "\1\13\11\0\4\13\1\0\1\13\2\310\1\13\1\15"+
    "\3\13\1\16\2\0\26\13\11\0\1\13\2\0\11\13"+
    "\1\0\2\13\6\0\1\13\11\0\4\13\1\0\4\13"+
    "\1\15\3\13\1\16\2\0\10\13\1\311\4\13\1\312"+
    "\10\13\11\0\1\13\2\0\4\13\1\312\1\13\1\311"+
    "\2\13\1\0\2\13\6\0\1\13\11\0\4\13\1\0"+
    "\4\13\1\15\3\13\1\16\2\0\15\13\1\313\10\13"+
    "\11\0\1\13\2\0\4\13\1\313\4\13\1\0\2\13"+
    "\6\0\1\13\11\0\4\13\1\0\4\13\1\15\3\13"+
    "\1\16\2\0\10\13\1\314\15\13\11\0\1\13\2\0"+
    "\6\13\1\314\2\13\1\0\2\13\6\0\1\13\11\0"+
    "\4\13\1\0\4\13\1\15\3\13\1\16\2\0\20\13"+
    "\1\315\5\13\11\0\1\13\2\0\3\13\1\315\5\13"+
    "\1\0\2\13\6\0\1\13\11\0\4\13\1\0\4\13"+
    "\1\15\3\13\1\16\2\0\26\13\11\0\1\13\2\0"+
    "\4\13\1\316\4\13\1\0\2\13\6\0\1\13\11\0"+
    "\4\13\53\0\1\317\65\0\1\320\73\0\4\13\1\15"+
    "\1\321\2\13\1\16\2\0\26\13\11\0\1\13\2\0"+
    "\11\13\1\0\2\13\6\0\1\13\11\0\4\13\53\0"+
    "\1\322\50\0\1\323\110\0\4\13\1\15\3\13\1\16"+
    "\2\0\26\13\11\0\1\13\2\0\1\324\10\13\1\0"+
    "\2\13\6\0\1\13\11\0\4\13\2\0\3\13\13\0"+
    "\4\13\1\0\2\13\3\0\2\13\2\0\2\13\54\0"+
    "\1\13\2\0\4\13\1\15\3\13\1\16\2\0\10\13"+
    "\1\325\15\13\11\0\1\13\2\0\6\13\1\325\2\13"+
    "\1\0\2\13\6\0\1\13\11\0\4\13\1\0\4\13"+
    "\1\15\3\13\1\16\2\0\15\13\1\326\10\13\11\0"+
    "\1\13\2\0\4\13\1\326\4\13\1\0\2\13\6\0"+
    "\1\13\11\0\4\13\1\0\4\13\1\15\3\13\1\16"+
    "\2\0\20\13\1\327\5\13\11\0\1\13\2\0\3\13"+
    "\1\327\5\13\1\0\2\13\6\0\1\13\11\0\4\13"+
    "\1\0\4\13\1\15\3\13\1\16\2\0\6\13\2\330"+
    "\16\13\11\0\1\13\2\0\11\13\1\0\2\13\6\0"+
    "\1\13\11\0\4\13\1\0\4\13\1\15\3\13\1\16"+
    "\2\0\6\13\2\331\16\13\11\0\1\13\2\0\11\13"+
    "\1\0\2\13\6\0\1\13\11\0\4\13\1\0\4\13"+
    "\1\15\3\13\1\16\2\0\14\13\1\332\11\13\11\0"+
    "\1\13\2\0\10\13\1\332\1\0\2\13\6\0\1\13"+
    "\11\0\4\13\37\0\1\333\137\0\1\334\35\0\4\13"+
    "\1\15\3\13\1\16\2\0\26\13\11\0\1\13\2\0"+
    "\1\335\10\13\1\0\2\13\6\0\1\13\11\0\4\13"+
    "\61\0\1\336\62\0\1\337\70\0\4\13\1\15\3\13"+
    "\1\16\2\0\26\13\11\0\1\13\2\0\4\13\1\340"+
    "\4\13\1\0\2\13\6\0\1\13\11\0\4\13\1\0"+
    "\4\13\1\15\3\13\1\16\2\0\10\13\1\341\15\13"+
    "\11\0\1\13\2\0\6\13\1\341\2\13\1\0\2\13"+
    "\6\0\1\13\11\0\4\13\1\0\4\13\1\15\3\13"+
    "\1\16\2\0\10\13\1\342\15\13\11\0\1\13\2\0"+
    "\6\13\1\342\2\13\1\0\2\13\6\0\1\13\11\0"+
    "\4\13\1\0\4\13\1\15\3\13\1\16\2\0\14\13"+
    "\1\343\11\13\11\0\1\13\2\0\10\13\1\343\1\0"+
    "\2\13\6\0\1\13\11\0\4\13\1\0\4\13\1\15"+
    "\3\13\1\16\2\0\20\13\1\344\5\13\11\0\1\13"+
    "\2\0\3\13\1\344\5\13\1\0\2\13\6\0\1\13"+
    "\11\0\4\13\1\0\4\13\1\15\3\13\1\16\2\0"+
    "\25\13\1\345\11\0\1\13\2\0\11\13\1\0\1\345"+
    "\1\13\6\0\1\13\11\0\4\13\1\0\4\13\1\15"+
    "\3\13\1\16\2\0\3\13\1\346\22\13\11\0\1\346"+
    "\2\0\11\13\1\0\2\13\6\0\1\13\11\0\4\13"+
    "\1\0\4\13\1\15\3\13\1\16\2\0\7\13\1\347"+
    "\16\13\11\0\1\13\2\0\11\13\1\0\2\13\6\0"+
    "\1\13\11\0\4\13\67\0\1\350\47\0\1\351\75\0"+
    "\4\13\1\15\3\13\1\16\2\0\3\13\1\352\22\13"+
    "\11\0\1\352\2\0\11\13\1\0\2\13\6\0\1\13"+
    "\11\0\4\13\1\0\4\13\1\15\3\13\1\16\2\0"+
    "\10\13\1\353\15\13\11\0\1\13\2\0\6\13\1\353"+
    "\2\13\1\0\2\13\6\0\1\13\11\0\4\13\1\0"+
    "\4\13\1\15\3\13\1\16\2\0\10\13\1\354\15\13"+
    "\11\0\1\13\2\0\6\13\1\354\2\13\1\0\2\13"+
    "\6\0\1\13\11\0\4\13\1\0\4\13\1\15\3\13"+
    "\1\16\2\0\15\13\1\355\10\13\11\0\1\13\2\0"+
    "\4\13\1\355\4\13\1\0\2\13\6\0\1\13\11\0"+
    "\4\13\71\0\1\356\114\0\1\357\26\0\4\13\1\15"+
    "\3\13\1\16\2\0\15\13\1\360\10\13\11\0\1\13"+
    "\2\0\4\13\1\360\4\13\1\0\2\13\6\0\1\13"+
    "\11\0\4\13\1\0\4\13\1\15\3\13\1\16\2\0"+
    "\10\13\1\361\15\13\11\0\1\13\2\0\6\13\1\361"+
    "\2\13\1\0\2\13\6\0\1\13\11\0\4\13\23\0"+
    "\1\362\75\0\1\363\113\0\4\13\1\15\3\13\1\16"+
    "\2\0\10\13\1\364\15\13\11\0\1\13\2\0\6\13"+
    "\1\364\2\13\1\0\2\13\6\0\1\13\11\0\4\13"+
    "\61\0\1\365\120\0\1\366\120\0\1\367\112\0\1\370"+
    "\115\0\1\371\120\0\1\372\111\0\1\373\110\0\1\374"+
    "\62\0\1\375\115\0\1\376\113\0\1\377\160\0\1\u0100"+
    "\117\0\1\u0101\112\0\1\u0102\71\0\1\u0103\131\0\1\u0104"+
    "\130\0\1\u0105\111\0\1\u0106\56\0\1\u0107\156\0\1\u0108"+
    "\64\0\1\u0109\150\0\1\u010a\55\0\1\u010b\155\0\1\u010c"+
    "\117\0\1\u010d\113\0\1\u010e\110\0\1\u010f\125\0\1\u0110"+
    "\24\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[14664];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\12\0\2\1\2\0\2\1\1\11\1\0\7\1\1\11"+
    "\2\1\2\11\3\1\1\11\1\1\1\11\1\1\1\11"+
    "\11\1\7\11\2\1\3\11\14\1\1\11\2\0\1\1"+
    "\1\11\2\1\3\11\1\1\1\11\1\1\1\11\1\1"+
    "\1\0\2\1\1\11\12\1\4\11\2\1\2\11\11\1"+
    "\1\11\1\0\3\11\2\1\2\11\11\1\4\11\1\1"+
    "\2\11\1\1\1\0\13\1\1\11\10\1\1\0\1\1"+
    "\2\11\3\1\1\0\1\1\1\11\2\1\1\0\14\1"+
    "\2\0\2\1\2\0\1\1\1\0\11\1\2\0\1\1"+
    "\2\0\7\1\2\11\1\1\2\0\10\1\2\0\4\1"+
    "\2\0\2\1\2\0\1\1\24\0\1\11\6\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[272];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  static private Stack<Integer> stateStack = new Stack<Integer>();
  
  // placeholder for the reserved word (keyword) table
  static private HashMap<String,Integer> keywords = null;
  
  // initialize the reserved word table as a static constructor
  static {
    keywords = new HashMap<String,Integer>();
    
    keywords.put("abs", CmlParser.ABS);
    //keywords.put("all", CmlParser.ALL);
    //keywords.put("always", CmlParser.ALWAYS);
    keywords.put("and", CmlParser.AND);
    keywords.put("atomic", CmlParser.ATOMIC);
    //keywords.put("async", CmlParser.ASYNC);
    //keywords.put("be", CmlParser.BE);
    keywords.put("bool", CmlParser.TBOOL);
    //keywords.put("by", CmlParser.BY);
    keywords.put("card", CmlParser.CARD);
    keywords.put("cases", CmlParser.CASES);
    keywords.put("char", CmlParser.TCHAR);
    keywords.put("class", CmlParser.CLASS);
    /*
    keywords.put("comp", CmlParser.COMP);
    keywords.put("compose", CmlParser.COMPOSE);
    keywords.put("conc", CmlParser.CONC);
    keywords.put("cycles", CmlParser.CYCLES);
    keywords.put("dcl", CmlParser.DCL);
    keywords.put("def", CmlParser.DEF);
    keywords.put("dinter", CmlParser.DINTER);
    keywords.put("div", CmlParser.ARITHMETIC_INTEGER_DIVISION);
    keywords.put("do", CmlParser.DO);
    keywords.put("dom", CmlParser.DOM);
    keywords.put("dunion", CmlParser.DUNION);
    keywords.put("duration", CmlParser.DURATION);
    keywords.put("elems", CmlParser.ELEMS);
    keywords.put("else", CmlParser.ELSE);
    keywords.put("elseif", CmlParser.ELSEIF);
    */
    keywords.put("end", CmlParser.END);
    /*
    keywords.put("error", CmlParser.ERROR);
    keywords.put("errs", CmlParser.ERRS);
    keywords.put("exists", CmlParser.EXISTS);
    keywords.put("exists1", CmlParser.EXISTS1);
    keywords.put("exit", CmlParser.EXIT);
    keywords.put("ext", CmlParser.EXT);
    keywords.put("false", CmlParser.bool_false);
    keywords.put("floor", CmlParser.FLOOR);
    keywords.put("for", CmlParser.FOR);
    keywords.put("forall", CmlParser.FORALL);
    keywords.put("from", CmlParser.FROM);
    keywords.put("functions", CmlParser.FUNCTIONS);
    keywords.put("hd", CmlParser.HD);
    keywords.put("if", CmlParser.IF);
    keywords.put("in", CmlParser.IN);
    keywords.put("inds", CmlParser.INDS);
    keywords.put("inmap", CmlParser.INMAP);
    keywords.put("instance", CmlParser.INSTANCE);
    keywords.put("int", CmlParser.INT);
    keywords.put("inter", CmlParser.SET_INTERSECTION);
    keywords.put("inv", CmlParser.INV);
    keywords.put("inverse", CmlParser.INVERSE);
    keywords.put("iota", CmlParser.IOTA);
    keywords.put("is", CmlParser.IS);
    keywords.put("is_", CmlParser.IS_);
    keywords.put("isofbaseclass", CmlParser.ISOFBASECLASS);
    keywords.put("isofclass", CmlParser.ISOFCLASS);
    keywords.put("lambda", CmlParser.LAMBDA);
    keywords.put("len", CmlParser.LEN);
    keywords.put("let", CmlParser.LET);
    keywords.put("map", CmlParser.MAP);
    keywords.put("merge", CmlParser.DMERGE);
    keywords.put("mk_", CmlParser.MK_);
    keywords.put("mod", CmlParser.MOD);
    keywords.put("mu", CmlParser.MU);
    keywords.put("munion", CmlParser.MAP_MERGE);
    keywords.put("mutex", CmlParser.MUTEX);
    */
    keywords.put("nat", CmlParser.TNAT);
    keywords.put("nat1", CmlParser.TNAT1);
    /*
    keywords.put("new", CmlParser.NEW);
    keywords.put("nil", CmlParser.NIL);
    keywords.put("not", CmlParser.NOT);
    keywords.put("of", CmlParser.OF);
    keywords.put("operations", CmlParser.OPERATIONS);
    keywords.put("or", CmlParser.OR);
    keywords.put("others", CmlParser.OTHERS);
    keywords.put("per", CmlParser.PER);
    keywords.put("periodic", CmlParser.PERIODIC);
    keywords.put("post", CmlParser.POST);
    keywords.put("power", CmlParser.POWER);
    keywords.put("pre", CmlParser.PRE);
    keywords.put("pre_", CmlParser.PRECONDAPPLY);
    */
    //keywords.put("private", CmlParser.PRIVATE);
    keywords.put("process", CmlParser.PROCESS);
    //keywords.put("protected", CmlParser.PROTECTED);
    keywords.put("psubset", CmlParser.PROPER_SUBSET);
    //keywords.put("public", CmlParser.PUBLIC);
    keywords.put("rat", CmlParser.TRAT);
    /*
    keywords.put("rd", CmlParser.VDMRD);
    */
    keywords.put("real", CmlParser.TREAL);
    /*
    keywords.put("rem", CmlParser.REM);
    keywords.put("responsibility", CmlParser.RESPONSIBILITY);
    keywords.put("return", CmlParser.RETURN);
    keywords.put("reverse", CmlParser.REVERSE);
    keywords.put("rng", CmlParser.RNG);
    keywords.put("samebaseclass", CmlParser.SAMEBASECLASS);
    keywords.put("sameclass", CmlParser.SAMECLASS);
    keywords.put("self", CmlParser.SELF);
    keywords.put("seq", CmlParser.SEQ);
    keywords.put("seq1", CmlParser.SEQ1);
    keywords.put("set", CmlParser.SET);
    keywords.put("skip", CmlParser.SKIP);
    keywords.put("specified", CmlParser.SPECIFIED);
    keywords.put("st", CmlParser.ST);
    keywords.put("start", CmlParser.START);
    keywords.put("startlist", CmlParser.STARTLIST);
    keywords.put("static", CmlParser.STATIC);
    keywords.put("subclass", CmlParser.SUBCLASS);
    keywords.put("subset", CmlParser.SUBSET);
    keywords.put("sync", CmlParser.SYNC);
    keywords.put("system", CmlParser.SYSTEM);
    keywords.put("then", CmlParser.THEN);
    keywords.put("thread", CmlParser.THREAD);
    keywords.put("threadid", CmlParser.THREADID);
    keywords.put("time", CmlParser.TIME);
    keywords.put("tixe", CmlParser.TIXE);
    keywords.put("tl", CmlParser.TL);
    keywords.put("to", CmlParser.TO);
    */
    keywords.put("token", CmlParser.TTOKEN);
    /*
    keywords.put("trap", CmlParser.TRAP);
    keywords.put("true", CmlParser.bool_true);
    */
    keywords.put("types", CmlParser.TYPES);
    //keywords.put("undefined", CmlParser.UNDEFINED);
    keywords.put("union", CmlParser.UNION);
    keywords.put("values", CmlParser.VALUES);
    keywords.put("variables", CmlParser.INSTANCEVARS);
    /*
    keywords.put("while", CmlParser.WHILE);
    keywords.put("with", CmlParser.WITH);
    keywords.put("wr", CmlParser.VDMWR);
    keywords.put("yet", CmlParser.YET);
    */
    
  }


  private CmlLexeme yylvalue;
  
  public int errors = 0;
public List<ParserError> parseErrors = new Vector<ParserError>();
  
    /**
     * Method to retrieve the beginning position of the last scanned token.
     * @return the position at which the last scanned token starts.  */
  public Position getStartPos () { return yylvalue.getStartPos(); }

    /**
     * Method to retrieve the ending position of the last scanned token.
     * @return the first position beyond the last scanned token.  */
  public Position getEndPos () { return yylvalue.getEndPos(); }

    /**
     * Method to retrieve the semantic value of the last scanned token.
     * @return the semantic value of the last scanned token.  */
  public Object getLVal () { return yylvalue; }
  
    /**
     * Entry point for error reporting.  Emits an error
     * referring to the given location in a user-defined way.
     *
     * @param loc The location of the element to which the
     *                error message is related
     * @param s The string for the error message.  */
  public void yyerror (Location loc, String err) { 
    
    System.err.println("Error : " + err + " at " + loc.begin.toString()); 
    
      String msg = new String(err);
	    if (yylvalue != null) {
	    	CmlLexeme currentToken = (CmlLexeme) yylvalue;
	    	if (currentToken.getValue().length() > 0) {
	    		// add position info iff the scanner found a lexem
	    	    msg += " at (" + currentToken.getStartPos().line + ", " + currentToken.getStartPos().column + ")";
	    		msg += " after reading token \"" + currentToken.getValue() + "\"";
	    		
	    		parseErrors.add(new ParserError(err+" after reading token \"" + currentToken.getValue() + "\"", 
	    		currentToken.getStartPos().line, currentToken.getStartPos().column));
	    	}
	    }
		System.out.println(msg);
		errors++;
    
  }
   

  // ************************************
  // *** AUXILIARY PRIVATE OPERATIONS ***
  // ************************************

  // helper function for checking reserved words and identifiers
  private int checkIdentifier(String id) {
      
      int line = yyline + 1;
      int column = yycolumn;
      String value = yytext();
      
      try {
	  if (keywords.containsKey(id)) {
	      //return new OmlLexem(line, column, new Long(keywords.get(id)), id, IOmlLexem.ILEXEMKEYWORD);
	      //return new CmlLexeme(line, column,IDENTIFIER, id);
	      yylvalue = new CmlLexeme(new Position(line,column),new Position(line,column + value.length()),keywords.get(id),value);
	      return keywords.get(id);
	      
	  } else {
	      //DEBUG String theText = yytext();
	      //DEBUG System.out.print(theText + " = ");
	      //DEBUG for (int idx=0; idx< theText.length(); idx++) System.out.format("%04x ", (int) theText.charAt(idx));
	      //DEBUG System.out.println();
	      //return new OmlLexem(line, column, new Long(LEX_identifier), id, IOmlLexem.ILEXEMIDENTIFIER);
	      //return new CmlLexeme(line, column, IDENTIFIER, id);
	      yylvalue = new CmlLexeme(new Position(line,column),new Position(line,column + value.length()),CmlParser.IDENTIFIER,value);
	      return CmlParser.IDENTIFIER;
	  }
      }
      catch (Exception cge) {
	  cge.printStackTrace();
	  return -1;
      }
  }
  
  // helper function for default token creation
  private int defaultToken()
  {
    return createToken(yytext().charAt(0));
  }
  
  
  /* Helper function to return the correct integer for the parser and create the correct Lexeme (semantic) values for the parser and beyond */
  private int createToken(int lex)
  {
    int line = yyline + 1;
    int column = yycolumn;
    String value = yytext();
    try {
      yylvalue = new CmlLexeme(new Position(line,column),new Position(line,column + value.length()),lex,value);
      //return new CmlLexeme(line, column, lex, yytext());
      return lex;
    }
    catch (Exception cge) {
      cge.printStackTrace();
      return -1;
    }
  }
  


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public CmlLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public CmlLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 188) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 25: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [637] { return createToken(CmlParser.LPAREN); }");
          { return createToken(CmlParser.LPAREN);
          }
        case 95: break;
        case 62: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [614] { return createToken(CmlParser.RNGSUB /*MAP_RANGE_RESTRICT_BY*/); }");
          { return createToken(CmlParser.RNGSUB /*MAP_RANGE_RESTRICT_BY*/);
          }
        case 96: break;
        case 37: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [620] { return createToken(CmlParser.IMPLY); }");
          { return createToken(CmlParser.IMPLY);
          }
        case 97: break;
        case 6: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [630] { return createToken(CmlParser.BACKTICK); }");
          { return createToken(CmlParser.BACKTICK);
          }
        case 98: break;
        case 17: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [643] { return createToken(CmlParser.RCURLY); }");
          { return createToken(CmlParser.RCURLY);
          }
        case 99: break;
        case 92: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [532] { yybegin(OPERATIONS); return createToken(CmlParser.OPERATIONS); }");
          { yybegin(OPERATIONS); return createToken(CmlParser.OPERATIONS);
          }
        case 100: break;
        case 73: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [561] { return createToken(CmlParser.OPERATIONARROW); }");
          { return createToken(CmlParser.OPERATIONARROW);
          }
        case 101: break;
        case 76: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [665] { return createToken(CmlParser.TBOOL); }");
          { return createToken(CmlParser.TBOOL);
          }
        case 102: break;
        case 57: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [589] { return createToken(CmlParser.RARROW); }");
          { return createToken(CmlParser.RARROW);
          }
        case 103: break;
        case 77: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [670] { return createToken(CmlParser.TREAL); }");
          { return createToken(CmlParser.TREAL);
          }
        case 104: break;
        case 2: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [682] { return createToken(CmlParser.symbolicLiteral); }");
          { return createToken(CmlParser.symbolicLiteral);
          }
        case 105: break;
        case 32: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [596] { return createToken(CmlParser.AT); }");
          { return createToken(CmlParser.AT);
          }
        case 106: break;
        case 29: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [592] { return createToken(CmlParser.AMP); }");
          { return createToken(CmlParser.AMP);
          }
        case 107: break;
        case 66: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [662] { return createToken(CmlParser.MKUNDER); }");
          { return createToken(CmlParser.MKUNDER);
          }
        case 108: break;
        case 49: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [552] { /*return createToken(CmlParser.VDMOF); */ }");
          { /*return createToken(CmlParser.VDMOF); */
          }
        case 109: break;
        case 5: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [652] { return createToken(CmlParser.SETDIFF); }");
          { return createToken(CmlParser.SETDIFF);
          }
        case 110: break;
        case 15: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [642] { return createToken(CmlParser.LCURLY); }");
          { return createToken(CmlParser.LCURLY);
          }
        case 111: break;
        case 88: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [571] { return createToken(CmlParser.MEASURE); }");
          { return createToken(CmlParser.MEASURE);
          }
        case 112: break;
        case 74: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [595] { return createToken(CmlParser.CSP_VARDECL); }");
          { return createToken(CmlParser.CSP_VARDECL);
          }
        case 113: break;
        case 3: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [680] { /* match whitespace; do nothing */ }");
          { /* match whitespace; do nothing */
          }
        case 114: break;
        case 13: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [647] { return createToken(CmlParser.GT); }");
          { return createToken(CmlParser.GT);
          }
        case 115: break;
        case 27: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [603] { return createToken(CmlParser.VDMTYPE); }");
          { return createToken(CmlParser.VDMTYPE);
          }
        case 116: break;
        case 8: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [645] { return createToken(CmlParser.DIV); }");
          { return createToken(CmlParser.DIV);
          }
        case 117: break;
        case 83: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [674] { return createToken(CmlParser.VDMSETOF); }");
          { return createToken(CmlParser.VDMSETOF);
          }
        case 118: break;
        case 79: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [569] { return createToken(CmlParser.POST); }");
          { return createToken(CmlParser.POST);
          }
        case 119: break;
        case 28: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [588] { return createToken(CmlParser.CSPSEQ); }");
          { return createToken(CmlParser.CSPSEQ);
          }
        case 120: break;
        case 20: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [641] { return createToken(CmlParser.RSQUARE); }");
          { return createToken(CmlParser.RSQUARE);
          }
        case 121: break;
        case 94: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [572] { return createToken(CmlParser.VDM_SUBCLASSRESP); }");
          { return createToken(CmlParser.VDM_SUBCLASSRESP);
          }
        case 122: break;
        case 47: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [616] { return createToken(CmlParser.DOTHASH); }");
          { return createToken(CmlParser.DOTHASH);
          }
        case 123: break;
        case 40: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [546] { return createToken(CmlParser.VDMTYPENCMP); }");
          { return createToken(CmlParser.VDMTYPENCMP);
          }
        case 124: break;
        case 81: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [530] { yybegin(TYPES); return createToken(CmlParser.TYPES); }");
          { yybegin(TYPES); return createToken(CmlParser.TYPES);
          }
        case 125: break;
        case 68: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [676] { return createToken(CmlParser.VDMINV); }");
          { return createToken(CmlParser.VDMINV);
          }
        case 126: break;
        case 72: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [564] { return createToken(CmlParser.VDM_EXT); }");
          { return createToken(CmlParser.VDM_EXT);
          }
        case 127: break;
        case 22: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [646] { return createToken(CmlParser.LT); }");
          { return createToken(CmlParser.LT);
          }
        case 128: break;
        case 55: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [582] { return createToken(CmlParser.CSP_CHANSET_END); }");
          { return createToken(CmlParser.CSP_CHANSET_END);
          }
        case 129: break;
        case 9: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [650] { return createToken(CmlParser.STAR); }");
          { return createToken(CmlParser.STAR);
          }
        case 130: break;
        case 46: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [619] { return createToken(CmlParser.NEQ); }");
          { return createToken(CmlParser.NEQ);
          }
        case 131: break;
        case 60: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [536] { yybegin(stateStack.pop()); return createToken(CmlParser.END); }");
          { yybegin(stateStack.pop()); return createToken(CmlParser.END);
          }
        case 132: break;
        case 91: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [531] { yybegin(FUNCTIONS); return createToken(CmlParser.FUNCTIONS); }");
          { yybegin(FUNCTIONS); return createToken(CmlParser.FUNCTIONS);
          }
        case 133: break;
        case 23: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [648] { return createToken(CmlParser.DOT); }");
          { return createToken(CmlParser.DOT);
          }
        case 134: break;
        case 19: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [640] { return createToken(CmlParser.LSQUARE); }");
          { return createToken(CmlParser.LSQUARE);
          }
        case 135: break;
        case 82: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [672] { return createToken(CmlParser.TTOKEN); }");
          { return createToken(CmlParser.TTOKEN);
          }
        case 136: break;
        case 31: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [594] { return createToken(CmlParser.CSP_CHANNEL_READ); }");
          { return createToken(CmlParser.CSP_CHANNEL_READ);
          }
        case 137: break;
        case 12: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [639] { return createToken(CmlParser.MINUS); }");
          { return createToken(CmlParser.MINUS);
          }
        case 138: break;
        case 85: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [565] { return createToken(CmlParser.RETURN); }");
          { return createToken(CmlParser.RETURN);
          }
        case 139: break;
        case 42: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [618] { return createToken(CmlParser.GTE); }");
          { return createToken(CmlParser.GTE);
          }
        case 140: break;
        case 58: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [597] { return createToken(CmlParser.CSPINTCH); }");
          { return createToken(CmlParser.CSPINTCH);
          }
        case 141: break;
        case 41: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [655] { return createToken(CmlParser.OR); }");
          { return createToken(CmlParser.OR);
          }
        case 142: break;
        case 61: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [654] { return createToken(CmlParser.AND); }");
          { return createToken(CmlParser.AND);
          }
        case 143: break;
        case 78: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [667] { return createToken(CmlParser.TNAT1); }");
          { return createToken(CmlParser.TNAT1);
          }
        case 144: break;
        case 84: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [658] { return createToken(CmlParser.INSET); }");
          { return createToken(CmlParser.INSET);
          }
        case 145: break;
        case 30: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [593] { return createToken(CmlParser.CSP_CHANNEL_WRITE); }");
          { return createToken(CmlParser.CSP_CHANNEL_WRITE);
          }
        case 146: break;
        case 1: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [681] { return createToken(CmlParser.IDENTIFIER); }");
          { return createToken(CmlParser.IDENTIFIER);
          }
        case 147: break;
        case 35: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [519] { stateStack.push(yystate()); yybegin(COMMENT); }");
          { stateStack.push(yystate()); yybegin(COMMENT);
          }
        case 148: break;
        case 16: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [638] { return createToken(CmlParser.BAR); }");
          { return createToken(CmlParser.BAR);
          }
        case 149: break;
        case 93: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [573] { return createToken(CmlParser.VDM_NOTYETSPEC); }");
          { return createToken(CmlParser.VDM_NOTYETSPEC);
          }
        case 150: break;
        case 53: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [563] { return createToken(CmlParser.VDM_WR); }");
          { return createToken(CmlParser.VDM_WR);
          }
        case 151: break;
        case 44: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [617] { return createToken(CmlParser.LTE); }");
          { return createToken(CmlParser.LTE);
          }
        case 152: break;
        case 45: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [627] { return createToken(CmlParser.DOMRES/*MAP_DOMAIN_RESTRICT_TO*/); }");
          { return createToken(CmlParser.DOMRES/*MAP_DOMAIN_RESTRICT_TO*/);
          }
        case 153: break;
        case 65: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [656] { return createToken(CmlParser.NOT); }");
          { return createToken(CmlParser.NOT);
          }
        case 154: break;
        case 11: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [633] { return createToken(CmlParser.COLON); }");
          { return createToken(CmlParser.COLON);
          }
        case 155: break;
        case 56: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [598] { return createToken(CmlParser.CSP_OPS_COM); }");
          { return createToken(CmlParser.CSP_OPS_COM);
          }
        case 156: break;
        case 64: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [666] { return createToken(CmlParser.TNAT); }");
          { return createToken(CmlParser.TNAT);
          }
        case 157: break;
        case 69: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [611] { return createToken(CmlParser.BIMPLY); }");
          { return createToken(CmlParser.BIMPLY);
          }
        case 158: break;
        case 26: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [651] { return createToken(CmlParser.CONC); }");
          { return createToken(CmlParser.CONC);
          }
        case 159: break;
        case 39: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [547] { return createToken(CmlParser.VDMRECORDDEF); }");
          { return createToken(CmlParser.VDMRECORDDEF);
          }
        case 160: break;
        case 86: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [526] { stateStack.push(yystate());yybegin(PROCESS); return createToken(CmlParser.PROCESS); }");
          { stateStack.push(yystate());yybegin(PROCESS); return createToken(CmlParser.PROCESS);
          }
        case 161: break;
        case 87: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [535] { yybegin(ACTIONS); return createToken(CmlParser.CSP_ACTIONS); }");
          { yybegin(ACTIONS); return createToken(CmlParser.CSP_ACTIONS);
          }
        case 162: break;
        case 36: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [548] { return createToken(CmlParser.DEQUALS); }");
          { return createToken(CmlParser.DEQUALS);
          }
        case 163: break;
        case 89: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [534] { yybegin(CHANSETS); return createToken(CmlParser.CHANSETS); }");
          { yybegin(CHANSETS); return createToken(CmlParser.CHANSETS);
          }
        case 164: break;
        case 7: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [629] { return createToken(CmlParser.TILDE /*HOOK*/); }");
          { return createToken(CmlParser.TILDE /*HOOK*/);
          }
        case 165: break;
        case 59: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [520] { yybegin(stateStack.pop()); }");
          { yybegin(stateStack.pop());
          }
        case 166: break;
        case 70: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [613] { return createToken(CmlParser.VDM_MAP_DOMAIN_RESTRICT_BY); }");
          { return createToken(CmlParser.VDM_MAP_DOMAIN_RESTRICT_BY);
          }
        case 167: break;
        case 24: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [636] { return createToken(CmlParser.RPAREN); }");
          { return createToken(CmlParser.RPAREN);
          }
        case 168: break;
        case 21: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [631] { return createToken(CmlParser.COMMA); }");
          { return createToken(CmlParser.COMMA);
          }
        case 169: break;
        case 71: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [570] { return createToken(CmlParser.PRE); }");
          { return createToken(CmlParser.PRE);
          }
        case 170: break;
        case 51: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [557] { return createToken(CmlParser.VDMTFUNCARROW); }");
          { return createToken(CmlParser.VDMTFUNCARROW);
          }
        case 171: break;
        case 90: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [533] { yybegin(CHANNELS); return createToken(CmlParser.CHANNELS); }");
          { yybegin(CHANNELS); return createToken(CmlParser.CHANNELS);
          }
        case 172: break;
        case 10: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [545] { return createToken(CmlParser.SEMI); }");
          { return createToken(CmlParser.SEMI);
          }
        case 173: break;
        case 54: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [581] { return createToken(CmlParser.CSP_CHANSET_BEGIN); }");
          { return createToken(CmlParser.CSP_CHANSET_BEGIN);
          }
        case 174: break;
        case 4: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [540] { return createToken(CmlParser.EQUALS); }");
          { return createToken(CmlParser.EQUALS);
          }
        case 175: break;
        case 52: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [562] { return createToken(CmlParser.VDM_RD); }");
          { return createToken(CmlParser.VDM_RD);
          }
        case 176: break;
        case 63: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [669] { return createToken(CmlParser.TRAT); }");
          { return createToken(CmlParser.TRAT);
          }
        case 177: break;
        case 33: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [521] { /* match comment text; do nothing */ }");
          { /* match comment text; do nothing */
          }
        case 178: break;
        case 38: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [623] { return createToken(CmlParser.ASSIGN); }");
          { return createToken(CmlParser.ASSIGN);
          }
        case 179: break;
        case 50: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [556] { return createToken(CmlParser.VDMPFUNCARROW); }");
          { return createToken(CmlParser.VDMPFUNCARROW);
          }
        case 180: break;
        case 48: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [621] { return createToken(CmlParser.DEQUALS /*IS_DEFINED_AS*/); }");
          { return createToken(CmlParser.DEQUALS /*IS_DEFINED_AS*/);
          }
        case 181: break;
        case 67: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [668] { return createToken(CmlParser.TINT); }");
          { return createToken(CmlParser.TINT);
          }
        case 182: break;
        case 14: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [644] { return createToken(CmlParser.PLUS); }");
          { return createToken(CmlParser.PLUS);
          }
        case 183: break;
        case 43: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [626] { return createToken(CmlParser.OVERWRITE /*MODIFY_BY*/); }");
          { return createToken(CmlParser.OVERWRITE /*MODIFY_BY*/);
          }
        case 184: break;
        case 34: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [518] { /* match comment; do nothing */ }");
          { /* match comment; do nothing */
          }
        case 185: break;
        case 80: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [541] { return createToken(CmlParser.BEGIN); }");
          { return createToken(CmlParser.BEGIN);
          }
        case 186: break;
        case 75: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [671] { return createToken(CmlParser.TCHAR); }");
          { return createToken(CmlParser.TCHAR);
          }
        case 187: break;
        case 18: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [649] {  }");
          { 
          }
        case 188: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {
                System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: <<EOF>>");
                System.out.println("action [688] { return 0; }");
                return 0;
              }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This main method is the debugging routine for the scanner.
   * It prints debugging information about each returned token to
   * System.out until the end of file is reached, or an error occured.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java CmlLexer <inputfile>");
    }
    else {
      for (int i = 0; i < argv.length; i++) {
        CmlLexer scanner = null;
        try {
          scanner = new CmlLexer( new java.io.FileReader(argv[i]) );
          do {
            System.out.println(scanner.yylex());
          } while (!scanner.zzAtEOF);

        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
