#!/bin/bash

BASE=`dirname $0`
REPO=$BASE/../..

JAR=$BASE/target/commandlinetool-*-jar-with-dependencies.jar
CLASSPATH=.:$REPO/core/parser/target/parser-*.jar:$REPO/core/ast/target/ast-*.jar

if [ ! -f ${JAR} ]; then
echo -e "Executable jar: \n\n${JAR}\n\ndoes not exists, type mvn package to build it."
exit -1;
fi

java -cp ${CLASSPATH} -jar ${JAR} $@
